export enum RabbitMQ {
  UserQueue = 'users',
  ProjectQueue = 'projects',
  SceneQueue = 'scenes',
  LinkHostpotQueue = 'linkHostpots',
  InfoHostpotQueue = 'infoHostpots',
}

export enum UserMSG {
  CREATE = 'CREATE_USER',
  FIND_ALL = 'FIND_USERS',
  FIND_ONE = 'FIND_USER',
  UPDATE = 'UPDATE_USER',
  DELETE = 'DELETE_USER',
  VALID_USER = 'VALID_USER',
  FIND_BY_EMAIL = 'FIND_BY_EMAIL',
  VALID_USERR = 'VALID_USERR',
  FIND_BY_PW = 'FIND_BY_PW',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  ADD_FAVORITE = 'ADD_FAVORITE',
  REMOVE_FAVORITE = 'REMOVE_FAVORITE',
  SEND_CODE = 'SEND_CODE',
  ADD_PER_VALIDATE = 'ADD_PER_VALIDATE',
  REMOVE_PER_VALIDATE = 'REMOVE_PER_VALIDATE',
  MAILED = 'MAILED',
  ASIGN_ROLE = 'ASIGN_ROLE',
  DELETE_USER = 'DELETE_USER',
  SEND_ACCEPTED_MAIL = 'SEND_ACCEPTED_MAIL',
  CHECK_MAIL = 'CHECK_MAIL',
  EXCEPT_ME = 'EXCEPT_ME',
  VALID_PASSWORD = 'VALID_PASSWORD',
}

export enum ProjectMSG {
  CREATE = 'CREATE_PROJECT',
  FIND_ALL = 'FIND_PROJECTS',
  FIND_ONE = 'FIND_PROJECT',
  UPDATE = 'UPDATE_PROJECT',
  DELETE = 'DELETE_PROJECT',
  UPLOAD = 'UPLOAD_IMG',
  FIND_ALL_BY_USER = 'FIND_ALL_BY_USER',
  ADD_LIKES = 'ADD_LIKES',
  REMOVE_LIKES = 'REMOVE_LIKES',
  FIND_UNVALIDED = 'FIND_UNVALIDED',
  VALIDATE_PROJECT = 'VALIDATE_PROJECT',
  FIND_VALIDED = 'FIND_VALIDED',
  UNVALIDATE_PROJECT = 'UNVALIDATE_PROJECT',
  FOR_REVISION = 'FOR_REVISION',
  TO_NEUTRAL = 'TO_NEUTRAL',
  ADD_COMMENT = 'ADD_COMMENT',
  REMOVE_COMMENT = 'REMOVE_COMMENT',
  FILTER_BY_STATUS = 'FILTER_BY_STATUS',
  CHANGE_USERNAME_PROJECT = 'CHANGE_USERNAME_PROJECT',
  EDIT_COMMENT = 'EDIT_COMMENT',
  ADD_RATE = 'ADD_RATE',
  DELETE_RATE = 'DELETE_RATE',
  EDIT_RATE = 'EDIT_RATE',
}

export enum SceneMSG {
  CREATE = 'CREATE_SCENE',
  FIND_ALL = 'FIND_SCENES',
  FIND_ONE = 'FIND_SCENE',
  UPDATE = 'UPDATE_SCENE',
  DELETE = 'DELETE_SCENE',
}

export enum LinkHostpotMSG {
  CREATE = 'CREATE_LINKHOSTPOT',
  FIND_ALL = 'FIND_LINKHOSTPOTS',
  FIND_ONE = 'FIND_LINKHOSTPOT',
  UPDATE = 'UPDATE_LINKHOSTPOT',
  DELETE = 'DELETE_LINKHOSTPOT',
}

export enum InfoHostpotMSG {
  CREATE = 'CREATE_INFOHOSTPOT',
  FIND_ALL = 'FIND_INFOHOSTPOTS',
  FIND_ONE = 'FIND_INFOHOSTPOT',
  UPDATE = 'UPDATE_INFOHOSTPOT',
  DELETE = 'DELETE_INFOHOSTPOT',
}

export const invalidTokens = new Set<string>();
